export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'

export const UPDATE_SLIDER = 'update_slider'
export const LOG_MOOD_SUCCESS = 'log_mood_success'
export const MOODS_FETCH_SUCCESS = 'moods_fetch_success'
export const UPDATE_COMPARED_ID = 'update_compared_id'
